### ISSUE TITLE
Please leave scores empty for any student that is not offering this subject.

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#10]
**_Please leave scores empty for any student that is not offering this subject._** 

I left scores empty for students not offering a particular subject but yet, the particular subject will still show in their report card and record zeros (0) all through for the subject not offering by the students.

I don't want the student to show at all in their report card, since they are not offering it.

Please what can I do?

**_Thanks in advance_**

**Comment by toliano** [comment]
Oh thanks I actually fixed this by adding this line of code to the query  **_AND (ca_score1+ca_score2+exam_score)>0_** 

to **_student/dashboard/result/result.php in line 153_** 

This remove the subjects not offering by the student cos at the end of the day the whole total is still zero (0)

**Comment by kelvin019** [comment]
Hello Toliano, 

Just saw this. Hope you are not uploading results from the admin?
The staff module is equipped with the result module and it's very effective.

Admin -> Staff Effectiveness is about 40% -> 100%.

In the current version v3, we have deprecated the result module for the admin and pushed the whole functionality to the stafff

**Comment by toliano** [comment]
Good day sir, I'm loving your good work especially this V3. The V3 solved all my issues and all. I can't thank you enough sir. God bless
