### ISSUE TITLE
Student Homework

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#12]
Well done on this great project sir's. Please I want to ask if it's possible for students to submit back solution to the given homework/assignment online from there portal?

Many Thanks

**Comment by kelvin019** [comment]
Hello,

We did not build that into the portal.
In future release of the portal, these features will be readily available.

Payment gateway Integration will also be added to the portal for fees and other payments.

Temporarily, you can collect the homework via other means.
