### ISSUE TITLE
Can't migrate to the next session

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#15]
Please I can't migrate to next session and I've put every other things in place (the tuition fee). I keep getting this error message.\

**"Heads up!There was an error performing the action. Contact developer"**

Please help

**Comment by kelvin019** [comment]
Hello,

Please locate this file (control/cpanel/switch_session.php) on your portal and insert the following codes below:

echo '<br />Promote all students: '. `$create_student_grade_year_mar;`
echo '<br />Disable Student Login: '. $kill_std_sessions_mar;
echo '<br />Set current Year: '. $db_set_current_yr_mar;
echo '<br />Remove Current Term: '. $remove_current_term_mar;
echo '<br />Current Term Set: '. $switch_to_first_term_mar;
echo '<br />Insert Fees Component: '. $set_fees_mar;
``
On Line 85: before the code:

if(($create_student_grade_year_mar > 0) and ($kill_std_sessions_mar >0) and ($db_set_current_yr_mar >0) and ($remove_current_term_mar >0) and ($switch_to_first_term_mar >0)  and ($set_fees_mar >0))


One of them is returning a "0" and that is why the session cant switch.

When you do this, give us the values of the code snippet above and we can assist you further..

**Comment by toliano** [comment]
Thanks so much for your response sir. I got the below output:

**_Promote all students: 0 Disable Student Login: 1 Set current Year: 1 Remove Current Term: 1 Current Term Set: 1 Insert Fees Component: 288_**

Thanks in advance

**Comment by kelvin019** [comment]
This simply means that the "promote students" code is returning a 0.
Do you have students in your database?

Can you give us access to the server so that we can check things for you?
Or perhaps, give us a copy of your database so that we can run things locally on our own servers?

These are the only possible fix to this.

**Comment by toliano** [comment]
Yes I haves students in the database but the script is hosted on a local server. Below is the link to the database:

_**https://drive.google.com/file/d/1CZ6nnHC2FpICr1eAXcKsi1JnEfbIIUk4/view?usp=sharing**_

Many Thanks in advance

**Comment by kelvin019** [comment]
Hello,

There was absolutely nothing wrong. The Session Switch was done after using your database.

First thing I noticed is:
You are going to be having issues in the "grades" table. **"KG 1"** and **"KG 2"** is having ID 11 and ID 12. This means that promotion from **"PRIMARY 6"** with ID 10 will be upgraded to **"KG 1"** which is very wrong.

You should have put the KG first before the Primaries. Consultation should have been made before Installing.

Possible Fix:

Copy the updated file from the server:
**control/cpanel/switch_session.php** and update it with yours. Then try running the "Switch Session Forward" action again. 

If it still dosent work, Uncomment line 129 and 130, run the "Switch Session Forward" again and paste the MYSQL code here. We will tell you what to do afterwards.

Regards

**Comment by toliano** [comment]
Thanks so much for your time sir. I did as  instructed, I replaced my switch_sesion with the latest one and yet it doesn't work. So I uncomment line 129 and 130, below is the SQL statement:

_**INSERT INTO student_grade_year (student_grade_year_student, student_grade_year_year, student_grade_year_grade) SELECT student_grade_year_student, 4 AS student_grade_year_year, student_grade_year_grade+1 AS student_grade_year_grade FROM student_grade_year WHERE student_grade_year_year = 3 AND student_grade_year_grade <= 11**_

many Thanks for your time sir

**Comment by toliano** [comment]
Although for the college which is different from the above, I had the same issue too, just that I changed the AND in line 183 to OR for the  _**  and ($set_fees_mar >0))**_.     So the portal was able to switch to 2021/2022 but not with the students, I had to assign each of the students to classes one by one.

[https://drive.google.com/file/d/1-PITxSgMZ9aNnMPAxPZMkAuWEQdydCni/view?usp=sharing](url)

_**Promote all students: 0 Disable Student Login: 0 Set current Year: 1 Remove Current Term: 1 Current Term Set: 1 Insert Fees Component: 288**_

SQL STATEMENT

_**INSERT INTO student_grade_year (student_grade_year_student, student_grade_year_year, student_grade_year_grade) SELECT student_grade_year_student, 3 AS student_grade_year_year, student_grade_year_grade+1 AS student_grade_year_grade FROM student_grade_year WHERE student_grade_year_year = 2 AND student_grade_year_grade <= 6**_

Many Thanks in advance

**Comment by impact0** [comment]
Please I have  the same issue. What do I do?

**Comment by kelvin019** [comment]
Hello,

Can you try running this software on your local server?
Try the switching forward and see if it runs. We have never had issues with switching forward and we are shocked you are experiencing these issues. 

If you followed the instructions for Installation, perhaps, this issues wont have occurred. Most issues are coming from the Database Schemas.

We are releasing another version of this same application with so many Bugs fix and perhaps, it will resolve your issues.

So sorry for the late replies.

**Comment by toliano** [comment]
Thanks for your response sir. Yes, I'm running the software on a local server and I tried it on both the WAMP SERVER and the XAMPP SERVER but still the same switching issue sir. May be when you finally release the new update sir. 

Thanks a million for your support. I can't just thank you enough.

**Comment by toliano** [comment]
Thank a million and a million times sir 🙏 🙏🙏🙏🙏🙏🙏the switching had been fixed perfectly fine. God bless you sir 🙏.

Please can I request for a demo link to the new version?
