### ISSUE TITLE
Disable Scratch Card For Student Registration

### ISSUE THREAD

**Issue by impact0** [ekumahost/my-complete-high-school-portal#16]
Greetings and I really appreciate your wonderful project. Please how can I disable scratch for student registration? 
Also, I find it difficult to migrate to another session afresh.

Please what can I do to resolve this?
Thanks

**Comment by kelvin019** [comment]
Hello,

Are you still having these issues?
The Scratch card cant be disabled. If its disabled, how do you want to handle fees payment? We can remove the moodle for scratch card and all that has to do with wallet but we need access to the server you used to deploy the project.

For the Migration issues, it has to do with your database Schema. Please try running the software on your localhost and see if you are able to Migrate sessions correctly.

Sorry for the extreme late reply. Things have kept us busy.
