### ISSUE TITLE
3rd term scores only

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#17]
Good day sir and thanks for your prompt support, its so amazing. Please I would like to know how I can display third term scores on the cumulative_report_card. 
I used:
```
 .$viewResultOpp->ca_score1.
 .$viewResultOpp->ca_score2.
 .$viewResultOpp->cexam_score.
```
but only 1st term scores were fetched but I need that of 3rd term only.

Thanks in advance

**Comment by kelvin019** [comment]
Hello Toliano,

Where are you viewing the cumulative report cards from?
Admin or the Staff portal?

The cumulative usually fetches all the terms.. From First to Third.
Let me know the script you are trying to edit and the screenshot of what you want to achieve.

Regards

**Comment by toliano** [comment]
I am viewing the result from STAFF PROFILE.

Yes, the cumulative do fetch all the terms scores by default (from 1st term to 3rd term but only in TOTAL_SUM). Just that I was trying to simplify the 3rd term scores only to be able to display (ca_score1, ca_score2, exam_score).

This is the script I am trying to edit [https://github.com/ekumahost/my-complete-high-school-portal/blob/master/student/dashboard/results/cumulative_view_result.php](https://github.com/ekumahost/my-complete-high-school-portal/blob/master/student/dashboard/results/cumulative_view_result.php)

And here is what I am trying to achieve [https://imgur.com/62KAp2k](https://imgur.com/62KAp2k)

Many Thanks sir.

**Comment by PENWELLJACKEY** [comment]
hi kindly assist im faiiling to install the website data-base

**Comment by kelvin019** [comment]
Can you send a mail to info@kastechnet.com?

**Comment by toliano** [comment]
Hello sir 🙏 thanks for the last time.

The cumulative display the three term score perfectly, but how can get the exact CA and EXAM score for just 3rd term alone?

Thanks in advance sir 🙏

**Comment by kelvin019** [comment]
Hello,

This is a pure customization feature. If you go through the code, you should be able to single out the third term.
