### ISSUE TITLE
Error creating a new session

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#2]
got this error message: "Out of idea! You cannot Switch forward without doing what is required. Next year is not created yet!
   
Ok, let me do it now"

![serror](https://user-images.githubusercontent.com/38895569/66703694-1d184b80-ed0d-11e9-815b-9ce63be5f9b2.PNG)

And have created the new session already on ground.

**Comment by ekumahost** [comment]
Please do what is required.
1. make sure you create school years
2. you are in first term and you want to go to next session, that is wrong, you have to enter third term first. the portal is intelligent.
3. have you also set school fee default for the new year you want to enter?
4. have you published students result for the current year?
START YOUR PORTAL FROM SCRATCH SO YOU CAN TRACK THE DOCUMENTATION AND HOW IT WORKS.
under /TOOLS look for the database that is fresh_install.sql use that database and start your portal afresh follow the instructions lets see if you will have issue. like I said, the one(database) you are using have dummy data.

**Comment by ekumahost** [comment]
It is not only year creation.
