### ISSUE TITLE
Disable E-mail authentication on Registratio

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#3]
Please am receiving could not sent whenever am trying to register as a staff. How can I disable this please?
![email not sent](https://user-images.githubusercontent.com/38895569/66819556-1a993a00-ef37-11e9-892b-748211c3b008.JPG)

**Comment by ekumahost** [comment]
go to the source code and change the message or make your mail to send(read installation process)

**Comment by toliano** [comment]
Though sir, I just want to disable the mail function. I don't want to the portal to send mail at all. what do i need to remove please?

Many Thanks.

**Comment by ekumahost** [comment]
you can just comment out something/.

**Comment by osotech** [comment]
Sir... I really want to use this opportunity to thank you for the great work you have done... But sir I am experiencing an error in the checking out of student and can't send staff and parent registration... I would be much happier and grateful if this can be solved.. Thanks a million

**Comment by osotech** [comment]
Just help to comment out email 📧 portion
