### ISSUE TITLE
Student Promotion/Deletion

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#4]
Good day sir, please how do I promote student from one class to another or how can I change their current class fro class A to class B.
Also, adding of subject is not working. 
And lastly, I can't delete student from the Portal.

Thanks in advance.

**Comment by ekumahost** [comment]
1. We did not write documentation on how to use the admin portal. but its user friendly.
all you need is look around find what you are looking for.
"promote student" is "change student class" under control in the right buttons .
 
2. if adding subject is not working state the error you see. we don't know the meaning of "not working"

3. if you cant delete student and you see any error while deleting student show it..
also student should not be deleted. the portal is automated. the same way you cant delete student from a school that is how you cannot delete student rather you can expel a student and write the reason why the student is expelled.

**Comment by ekumahost** [comment]
as for adding subject it is fixed now and update is pushed to git.
