### ISSUE TITLE
Checking out issues 

### ISSUE THREAD

**Issue by osotech** [ekumahost/my-complete-high-school-portal#5]
Sir at the student dashboard.. When check out button is clicked.. I received an error message.. Sir pls do help with this

**Comment by kelvin019** [comment]
Hello. Please what is the error message? So we can tell you how to fix it. Make sure you have configured the javascript config file in the js folder.

**Comment by osotech** [comment]
Parent, staff and student were unable to check out. The button is not functioning.. And hostel module not functioning at student portal

**Comment by kelvin019** [comment]
The Hostel module is still worked on. Still yet to be complete. Can you give us access to the server to fix the logout issue? Or you prefer we try fixing it from here?

**Comment by kelvin019** [comment]
`Or` lets do this. Locate the file below:
myjs/feccukcontroller.js

1. Change the "server_root_dir" to your website url (Change from localhost) e.g, yiour websitename.com/  - Make sure you add a forward-trailing slash
2. Replace the "loadingInit" function file, with

var loadingInit = $("<div id='still_loading' />").css({
    position: "fixed",
    top: "50%",
    left: "45%",
    color: "#000",
    padding: "16px 20px",
    background: "#FFF",
    "z-index": "10899737",
    "box-shadow": "4px 4px 14px #000",
    "border": "2px solid #000"
}).html("Loading Content... <img src='"+ server_root_dir +"img/ajax-loader.gif' width='32' alt='Please Wait...' />");

After doing these, clear your cache and try again. It should work now.
