### ISSUE TITLE
I Need Help Please

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#8]
Please I need assistance on cumulative result, singularly 1st term and 2nd term results display on their own. But on the cumulative page, only the 2nd term result is displaying while 1st term column is blank (No error message is display).

Thanks in advance

**Comment by kelvin019** [comment]
Hello,

The cummulative result is on what page exactly?
The admin or the Staff?

Have you checked if the result is existing on the portal?
Can we have screenshots of what you are seeing?

**Comment by toliano** [comment]
It is on the student folder. Though I fixed that by re-installing the portal again
