### ISSUE TITLE
Unable to credit students wallet

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#9]
Hello sir, well done out there and I hope everything is going on well?

Please I always get this error message (Fatal Error: Could not Credit your Balance. Please Try Again.) each time I tried to recharge students wallet after inserting the Serial/Pin. Below is a link to the error message image.
[Error Message](https://imgur.com/NdoRaEG)     Please kindly assist in looking into this issue

Many Thanks

**Comment by kelvin019** [comment]
Hello,

Try this. Use the pin as the serial and the serial as the pin. i.e Invert the fields and try again.
Some times, the representation on the admin end is different from what it may seem.

If it still dosent work, let us know so that we can update this script.

**Comment by kelvin019** [comment]
Hello,

I have checked the codes again and did not find any issue.
Make sure you have the right codes and serial.

You can update the one you have on your server by replacing the file on:
/student/dashboard/wallet/wallet_recharge_processor.php

with the one we have here now.

If the issue persist, you may release your login information (server, student and admin logon) so that we can check it out for you.

**Comment by toliano** [comment]
Sir, its still showing the same error message. It was hosted locally on WAMP SERVER sir

**Comment by kelvin019** [comment]
Hello,

Sorry if you are still having this issue.
Can we have a screenshot of the database table "student_wallet_pins"?

You can try clearing the table and then recreate the pins again.
Send the new screenshot to us for further audit.'

We should be able to assist you further.

**Comment by toliano** [comment]
Thanks for your response sir. Below is the table to student_wallet_pins

[student_wallet_pins](https://imgur.com/xVJswJi)
[student_wallet_pins](https://imgur.com/wBBwxOH)

Thanks in advance

**Comment by kelvin019** [comment]
Hello Toliano,

Are you still having this issue?

**Comment by toliano** [comment]
Yes sir. I am still experiencing the issue
